Repository AY2223S1-CS2103-W14-2/tp, pull requests merged in 2022-09, with the labels that each got.

#1 Update index.md of documentation with app name
  docs/_config.yml
  docs/index.md
Labels: documentation

#33 Update name to FoodWhere for sitewide settings
  docs/_data/projects.yml
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.High

#38 Add user stories and use cases 1 - 5 in Developer Guide for v1.1
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#42 Add more use cases to Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#51 Update page 7 in User Guide for v1.1
  docs/UserGuide.md
Labels: type.Task, priority.High

#52 Create PPP-Lik Hern for v1.1
  docs/team/likhern.md
Labels: type.Task, priority.High

#56 Remove placeholder images and page in AboutUs for v1.1
  docs/AboutUs.md
  docs/images/johndoe.png
  docs/team/johndoe.md
Labels: type.Task, priority.High

#54 Remove homepage URL for Chung Loong in AboutUs
  docs/AboutUs.md
Labels: type.Task, priority.High

#77 Update README.md with correct link to CI actions
  README.md
Labels: type.Bug, priority.High, severity.VeryLow

#81 Modify build.gradle to use foodwhere
  build.gradle
Labels: type.Task, priority.High

#44 Add new user guide URL to Help menu
  src/main/java/foodwhere/ui/HelpWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#46 Add new ListPanel for food reviews
  copyright.txt
  src/main/java/foodwhere/ui/MainWindow.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/ReviewListPanel.java
  src/main/java/foodwhere/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/food-where_icon.png
  src/main/resources/images/review.png
  src/main/resources/images/stall.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReviewListCard.fxml
  src/main/resources/view/ReviewListPanel.fxml
  src/test/java/foodwhere/commons/util/AppUtilTest.java
Labels: type.Task, priority.High
