Repository AY2223S1-CS2103-W14-2/tp, pull requests merged in 2022-11, with the labels that each got.

#265 Add use case for sort commands
  docs/DeveloperGuide.md
Labels: documentation, type.Task, priority.High

#261 Add use case for Find Command in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#329 Add new test cases to increase code coverage
  src/main/java/foodwhere/model/AddressBook.java
  src/main/java/foodwhere/model/stall/StallBuilder.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/test/java/foodwhere/AppParametersTest.java
  src/test/java/foodwhere/commons/core/VersionTest.java
  src/test/java/foodwhere/model/AddressBookTest.java
  src/test/java/foodwhere/model/ModelManagerTest.java
  src/test/java/foodwhere/model/UserPrefsTest.java
  src/test/java/foodwhere/model/util/SampleDataUtilTest.java
Labels: type.Task, priority.High

#263 Update PPP for Chung Loong
  docs/team/hikoya.md
Labels: documentation, type.Task, priority.High

#333 Modify invalid index error message to be standardized
  src/main/java/foodwhere/commons/core/Messages.java
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/commands/RDeleteCommand.java
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/main/java/foodwhere/logic/commands/SDeleteCommand.java
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/logic/parser/RAddCommandParser.java
  src/main/java/foodwhere/logic/parser/RDeleteCommandParser.java
  src/main/java/foodwhere/logic/parser/REditCommandParser.java
  src/main/java/foodwhere/logic/parser/SDeleteCommandParser.java
  src/main/java/foodwhere/logic/parser/SEditCommandParser.java
  src/test/java/foodwhere/logic/LogicManagerTest.java
  src/test/java/foodwhere/logic/commands/RAddCommandTest.java
  src/test/java/foodwhere/logic/commands/RDeleteCommandTest.java
  src/test/java/foodwhere/logic/commands/SDeleteCommandTest.java
  src/test/java/foodwhere/logic/commands/SEditCommandTest.java
  src/test/java/foodwhere/logic/parser/RDeleteCommandParserTest.java
  src/test/java/foodwhere/logic/parser/SDeleteCommandParserTest.java
  src/test/java/foodwhere/logic/parser/SEditCommandParserTest.java
Labels: bug, priority.High, severity.Low

#334 Update minheina PPP
  docs/team/minheina.md
Labels: documentation, type.Task, priority.High

#323 Update PPP for Clarence
  docs/team/clarence-chew.md
Labels: documentation, type.Task

#339 Update Developer Guide to fix numbering
  docs/DeveloperGuide.md
Labels: bug, priority.High, severity.VeryLow

#332 Update developer guide for sorting feature
  docs/DeveloperGuide.md
  docs/diagrams/SortReviewActivityDiagram.puml
  docs/images/SortReviewActivityDiagram.png
Labels: documentation, type.Task, priority.High

#327 Update PPP for Jamie
  docs/DeveloperGuide.md
  docs/team/jamietan2002.md
Labels: documentation, type.Task

#341 Improve code coverage for find functions
  src/test/java/foodwhere/logic/parser/RFindCommandParserTest.java
  src/test/java/foodwhere/logic/parser/SFindCommandParserTest.java
Labels: type.Task, priority.Medium

#346 Update PPP for Lik Hern
  docs/team/likhern.md
Labels: documentation, type.Task, priority.High

#337 Improve test coverage for utility methods and classes
  src/main/java/foodwhere/logic/commands/RDeleteCommand.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/model/review/Date.java
  src/main/java/foodwhere/model/review/comparator/DateComparator.java
  src/main/java/foodwhere/model/review/comparator/NameComparator.java
  src/main/java/foodwhere/model/review/comparator/RatingComparator.java
  src/main/java/foodwhere/model/stall/comparator/NameComparator.java
  src/test/java/foodwhere/commons/core/LogsCenterTest.java
  src/test/java/foodwhere/logic/LogicManagerTest.java
  src/test/java/foodwhere/logic/commands/CommandResultTest.java
  src/test/java/foodwhere/logic/commands/RAddCommandTest.java
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/model/review/RatingTest.java
  src/test/java/foodwhere/model/review/comparator/DateComparatorTest.java
  src/test/java/foodwhere/model/review/comparator/NameComparatorTest.java
  src/test/java/foodwhere/model/review/comparator/RatingComparatorTest.java
  src/test/java/foodwhere/model/review/comparator/ReviewsComparatorListTest.java
  src/test/java/foodwhere/model/stall/StallTest.java
  src/test/java/foodwhere/model/stall/comparator/NameComparatorTest.java
  src/test/java/foodwhere/model/stall/comparator/StallsComparatorListTest.java
Labels: type.Task, priority.Medium

#348 Update Developer Guide to include ssort
  docs/DeveloperGuide.md
  docs/diagrams/SortActivityDiagram.puml
  docs/images/SortActivityDiagram.png
  docs/images/SortReviewActivityDiagram.png
Labels: documentation, type.Task, priority.High

#350 Update user guide and fix JsonAdaptedStall parsing
  docs/UserGuide.md
  src/main/java/foodwhere/logic/commands/RFindCommand.java
  src/main/java/foodwhere/logic/commands/SFindCommand.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
Labels: bug, documentation

#351 Improve Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelReviewClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/images/ModelClassDiagram.png
  docs/images/ModelReviewClassDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
Labels: documentation

#354 Add new test cases for RAddCommandParser
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/parser/RAddCommandParserTest.java
  src/test/java/foodwhere/model/commons/AddressTest.java
  src/test/java/foodwhere/model/commons/NameTest.java
  src/test/java/foodwhere/model/commons/TagTest.java
Labels: type.Task, priority.Medium

#356 Update PPP for Chung Loong
  docs/team/hikoya.md
Labels: documentation, type.Task, priority.Medium

#357 Add REdit and REditCommandParser Unit tests
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/REditCommandTest.java
  src/test/java/foodwhere/logic/parser/REditCommandParserTest.java
  src/test/java/foodwhere/testutil/EditReviewDescriptorBuilder.java
  src/test/java/foodwhere/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#360 Add @@author tags to reused code
  docs/team/hikoya.md
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/ReviewListPanel.java
  src/main/java/foodwhere/ui/StallCard.java
  src/main/java/foodwhere/ui/StallListPanel.java
Labels: documentation, type.Task, priority.High

#349 Add Manual Test Instructions
  docs/DeveloperGuide.md
Labels: documentation, type.Task, priority.High

#363 Fix REdit tests
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/REditCommandTest.java
  src/test/java/foodwhere/logic/parser/REditCommandParserTest.java
Labels: bug, type.Task

#365 Edit Developer Guide for clarity
  docs/DeveloperGuide.md
  docs/images/sfind.png
  docs/team/hikoya.md
Labels: documentation, type.Task, priority.High

#362 Add test cases for sort commands
  src/main/java/foodwhere/logic/commands/RSortCommand.java
  src/main/java/foodwhere/logic/commands/SSortCommand.java
  src/test/java/foodwhere/logic/commands/RSortCommandTest.java
  src/test/java/foodwhere/logic/commands/SSortCommandTest.java
  src/test/java/foodwhere/logic/parser/AddressBookParserTest.java
  src/test/java/foodwhere/logic/parser/RSortCommandParserTest.java
  src/test/java/foodwhere/logic/parser/SSortCommandParserTest.java
Labels: documentation, type.Task, priority.High

#369 Modify JavaDoc comments for classes
  src/main/java/foodwhere/commons/core/Messages.java
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/commands/RDeleteCommand.java
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/main/java/foodwhere/logic/commands/RFindCommand.java
  src/main/java/foodwhere/logic/commands/RSortCommand.java
  src/main/java/foodwhere/logic/commands/SAddCommand.java
  src/main/java/foodwhere/logic/commands/SDeleteCommand.java
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/logic/commands/SFindCommand.java
  src/main/java/foodwhere/logic/commands/SSortCommand.java
  src/main/java/foodwhere/logic/parser/RAddCommandParser.java
  src/main/java/foodwhere/logic/parser/RDeleteCommandParser.java
  src/main/java/foodwhere/logic/parser/REditCommandParser.java
  src/main/java/foodwhere/logic/parser/RFindCommandParser.java
  src/main/java/foodwhere/logic/parser/RSortCommandParser.java
  src/main/java/foodwhere/logic/parser/SAddCommandParser.java
  src/main/java/foodwhere/logic/parser/SDeleteCommandParser.java
  src/main/java/foodwhere/logic/parser/SEditCommandParser.java
  src/main/java/foodwhere/logic/parser/SFindCommandParser.java
  src/main/java/foodwhere/logic/parser/SSortCommandParser.java
  src/main/java/foodwhere/model/AddressBook.java
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/model/UserPrefs.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/review/UniqueReviewList.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/stall/UniqueStallList.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonUserPrefsStorage.java
  src/main/java/foodwhere/storage/StorageManager.java
  src/main/java/foodwhere/ui/CopyMenuItem.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/ReviewListPanel.java
  src/main/java/foodwhere/ui/StallCard.java
  src/test/java/foodwhere/model/review/UniqueReviewListTest.java
Labels: documentation, type.Task, priority.High

#372 Fix minor formatting details for PPP
  docs/team/jamietan2002.md
Labels: documentation, type.Task, priority.High

#374 Fix PPP for Chung Loong
  docs/team/hikoya.md
Labels: bug, documentation, severity.VeryLow

#380 Modify JavaDocs to follow coding standard
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/main/java/foodwhere/logic/commands/RListCommand.java
  src/main/java/foodwhere/logic/commands/RSortCommand.java
  src/main/java/foodwhere/logic/commands/SAddCommand.java
  src/main/java/foodwhere/logic/commands/SDeleteCommand.java
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/logic/commands/SFindCommand.java
  src/main/java/foodwhere/logic/commands/SListCommand.java
  src/main/java/foodwhere/logic/commands/SSortCommand.java
  src/main/java/foodwhere/logic/parser/RAddCommandParser.java
  src/main/java/foodwhere/logic/parser/RDeleteCommandParser.java
  src/main/java/foodwhere/logic/parser/REditCommandParser.java
  src/main/java/foodwhere/logic/parser/RFindCommandParser.java
  src/main/java/foodwhere/logic/parser/RSortCommandParser.java
  src/main/java/foodwhere/logic/parser/SAddCommandParser.java
  src/main/java/foodwhere/logic/parser/SDeleteCommandParser.java
  src/main/java/foodwhere/logic/parser/SEditCommandParser.java
  src/main/java/foodwhere/logic/parser/SFindCommandParser.java
  src/main/java/foodwhere/logic/parser/SSortCommandParser.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/model/ReadOnlyAddressBook.java
  src/main/java/foodwhere/model/commons/Address.java
  src/main/java/foodwhere/model/commons/Name.java
  src/main/java/foodwhere/model/commons/Tag.java
  src/main/java/foodwhere/model/review/Content.java
  src/main/java/foodwhere/model/review/Date.java
  src/main/java/foodwhere/model/review/Rating.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/review/ReviewContainsKeywordsPredicate.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/stall/StallContainsKeywordsPredicate.java
  src/main/java/foodwhere/storage/AddressBookStorage.java
  src/main/java/foodwhere/storage/JsonUserPrefsStorage.java
  src/main/java/foodwhere/storage/UserPrefsStorage.java
  src/main/java/foodwhere/ui/HelpWindow.java
  src/main/java/foodwhere/ui/MainWindow.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
  src/main/java/foodwhere/ui/Ui.java
  src/main/java/foodwhere/ui/UiPart.java
Labels: documentation, type.Task, priority.High

#378 Fix Developer Guide for some formatting issues
  docs/DeveloperGuide.md
Labels: documentation, type.Task, priority.High

#376 Change "capitalisation" to "capitalization"
  docs/UserGuide.md
Labels: documentation

#381 Improve DG
  docs/DeveloperGuide.md
Labels: bug, documentation

#384 Modify PPP for Chung Loong to remove extra ]
  docs/team/hikoya.md
Labels: documentation, type.Task, priority.High

#388 Standardize RDel and REdit sequence diagrams
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/REditSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/REditSequenceDiagram.png
Labels: documentation, priority.High

#386 Update minheina PPP
  docs/team/minheina.md
Labels: documentation, type.Task, priority.High

#389 Improve sequence diagram resolution
  docs/images/DeleteSequenceDiagram.png
  docs/images/REditSequenceDiagram.png
Labels: documentation, type.Task, priority.High

#392 Improve PPP for clarence-chew
  docs/team/clarence-chew.md
Labels: documentation

#394 Fix DG Contents page visual bug
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Low
