Repository AY2223S1-CS2103-W14-2/tp, pull requests merged in 2022-10, with the labels that each got.

#84 Modify tag to detail
  src/main/java/foodwhere/logic/commands/AddCommand.java
  src/main/java/foodwhere/logic/commands/EditCommand.java
  src/main/java/foodwhere/logic/parser/AddCommandParser.java
  src/main/java/foodwhere/logic/parser/CliSyntax.java
  src/main/java/foodwhere/logic/parser/EditCommandParser.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/model/detail/Detail.java
  src/main/java/foodwhere/model/person/Person.java
  src/main/java/foodwhere/model/tag/Tag.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedDetail.java
  src/main/java/foodwhere/storage/JsonAdaptedPerson.java
  src/main/java/foodwhere/storage/JsonAdaptedTag.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/foodwhere/logic/LogicManagerTest.java
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/EditCommandTest.java
  src/test/java/foodwhere/logic/commands/EditPersonDescriptorTest.java
  src/test/java/foodwhere/logic/parser/AddCommandParserTest.java
  src/test/java/foodwhere/logic/parser/EditCommandParserTest.java
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/model/AddressBookTest.java
  src/test/java/foodwhere/model/detail/DetailTest.java
  src/test/java/foodwhere/model/person/PersonTest.java
  src/test/java/foodwhere/model/person/UniquePersonListTest.java
  src/test/java/foodwhere/model/tag/TagTest.java
  src/test/java/foodwhere/storage/JsonAdaptedPersonTest.java
  src/test/java/foodwhere/testutil/EditPersonDescriptorBuilder.java
  src/test/java/foodwhere/testutil/PersonBuilder.java
  src/test/java/foodwhere/testutil/PersonUtil.java
  src/test/java/foodwhere/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#86 Branch delete email data class
  src/main/java/foodwhere/logic/commands/AddCommand.java
  src/main/java/foodwhere/logic/commands/EditCommand.java
  src/main/java/foodwhere/logic/parser/AddCommandParser.java
  src/main/java/foodwhere/logic/parser/CliSyntax.java
  src/main/java/foodwhere/logic/parser/EditCommandParser.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/model/person/Email.java
  src/main/java/foodwhere/model/person/Person.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedPerson.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/foodwhere/logic/LogicManagerTest.java
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/EditPersonDescriptorTest.java
  src/test/java/foodwhere/logic/parser/AddCommandParserTest.java
  src/test/java/foodwhere/logic/parser/EditCommandParserTest.java
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/model/person/EmailTest.java
  src/test/java/foodwhere/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/foodwhere/model/person/PersonTest.java
  src/test/java/foodwhere/storage/JsonAdaptedPersonTest.java
  src/test/java/foodwhere/testutil/EditPersonDescriptorBuilder.java
  src/test/java/foodwhere/testutil/PersonBuilder.java
  src/test/java/foodwhere/testutil/PersonUtil.java
  src/test/java/foodwhere/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#88 Remove email from User Interface
  src/main/resources/view/ReviewListCard.fxml
  src/main/resources/view/StallListCard.fxml
Labels: type.Task, priority.High

#90 Update Detail.java to fix JavaDocs bug
  src/main/java/foodwhere/model/detail/Detail.java
Labels: type.Bug, severity.Low

#94 Modify DeveloperGuide.md without reference to command
  docs/DeveloperGuide.md
Labels: type.Bug, priority.High, severity.VeryLow

#97 Branch delete phone data class
  src/main/java/foodwhere/logic/commands/AddCommand.java
  src/main/java/foodwhere/logic/commands/EditCommand.java
  src/main/java/foodwhere/logic/parser/AddCommandParser.java
  src/main/java/foodwhere/logic/parser/CliSyntax.java
  src/main/java/foodwhere/logic/parser/EditCommandParser.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/model/stall/Phone.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStallAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStallAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStallAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStallAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStallsAddressBook.json
  src/test/java/foodwhere/logic/LogicManagerTest.java
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/EditCommandTest.java
  src/test/java/foodwhere/logic/commands/EditStallDescriptorTest.java
  src/test/java/foodwhere/logic/parser/AddCommandParserTest.java
  src/test/java/foodwhere/logic/parser/EditCommandParserTest.java
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/model/stall/NameContainsKeywordsPredicateTest.java
  src/test/java/foodwhere/model/stall/PhoneTest.java
  src/test/java/foodwhere/model/stall/StallTest.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
  src/test/java/foodwhere/testutil/EditStallDescriptorBuilder.java
  src/test/java/foodwhere/testutil/StallBuilder.java
  src/test/java/foodwhere/testutil/StallUtil.java
  src/test/java/foodwhere/testutil/TypicalStalls.java
Labels: type.Task, priority.High

#99 Remove phone field from user interface
  src/main/resources/view/ReviewListCard.fxml
  src/main/resources/view/StallListCard.fxml
Labels: type.Task, priority.High

#95 Handle storage of Stall using JsonAdaptedStall
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
Labels: type.Task, priority.High

#106 Add Review.java and related classes
  src/main/java/foodwhere/model/review/Date.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/review/StallName.java
  src/main/java/foodwhere/model/review/UniqueReviewList.java
  src/main/java/foodwhere/model/review/exceptions/DuplicateReviewException.java
  src/main/java/foodwhere/model/review/exceptions/ReviewNotFoundException.java
Labels: type.Task, priority.High

#108 Add content class as a constant field under review class
  src/main/java/foodwhere/model/review/Content.java
  src/main/java/foodwhere/model/review/Review.java
Labels: type.Task, priority.High

#110 Add Review as Stall's data class
  src/main/java/foodwhere/model/stall/Stall.java
Labels: type.Task, priority.High

#114 Modify CI and Codecov link in index.md for Github pages
  docs/index.md
Labels: type.Task, priority.High

#119 Modify common fields to new package models.common
  src/main/java/foodwhere/logic/commands/EditCommand.java
  src/main/java/foodwhere/logic/parser/EditCommandParser.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/logic/parser/SAddCommandParser.java
  src/main/java/foodwhere/model/commons/Detail.java
  src/main/java/foodwhere/model/commons/Name.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/stall/Name.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedDetail.java
  src/main/java/foodwhere/storage/JsonAdaptedReview.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/test/java/foodwhere/logic/parser/EditCommandParserTest.java
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/logic/parser/SAddCommandParserTest.java
  src/test/java/foodwhere/model/detail/DetailTest.java
  src/test/java/foodwhere/model/stall/NameTest.java
  src/test/java/foodwhere/storage/JsonAdaptedReviewTest.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
  src/test/java/foodwhere/testutil/EditStallDescriptorBuilder.java
  src/test/java/foodwhere/testutil/ReviewBuilder.java
  src/test/java/foodwhere/testutil/StallBuilder.java
  src/test/java/foodwhere/testutil/StallUtil.java
Labels: type.Task, priority.High

#122 Remove reference to Name class in ReviewBuilder and JSONAdaptedReview
  src/main/java/foodwhere/storage/JsonAdaptedReview.java
  src/test/java/foodwhere/testutil/ReviewBuilder.java
Labels: type.Task, priority.Medium

#125 Modify Ui.png to current user interface
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/Ui.png
Labels: type.Task, priority.Medium

#126 Modify user interface to use Review as list
  src/main/java/foodwhere/logic/Logic.java
  src/main/java/foodwhere/logic/LogicManager.java
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/ui/MainWindow.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/ReviewListPanel.java
  src/main/java/foodwhere/ui/StallCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReviewListCard.fxml
  src/main/resources/view/StallListCard.fxml
  src/test/java/foodwhere/logic/commands/SAddCommandTest.java
Labels: type.Task, priority.High

#127 Add RAddCommand
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/parser/AddressBookParser.java
  src/main/java/foodwhere/logic/parser/CliSyntax.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/logic/parser/RAddCommandParser.java
  src/main/java/foodwhere/model/Model.java
Labels: type.Task, priority.High

#128 Add RDeleteCommand
  src/main/java/foodwhere/commons/core/Messages.java
  src/main/java/foodwhere/logic/commands/RDeleteCommand.java
  src/main/java/foodwhere/logic/parser/AddressBookParser.java
  src/main/java/foodwhere/logic/parser/RDeleteCommandParser.java
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/RDeleteCommandTest.java
  src/test/java/foodwhere/logic/commands/SAddCommandTest.java
  src/test/java/foodwhere/logic/parser/RDeleteCommandParserTest.java
  src/test/java/foodwhere/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#130 Add test coverage for review data classes
  src/test/data/JsonSerializableAddressBookTest/typicalStallsAddressBook.json
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/model/review/ContentTest.java
  src/test/java/foodwhere/model/review/DateTest.java
  src/test/java/foodwhere/model/review/ReviewTest.java
  src/test/java/foodwhere/model/review/UniqueReviewListTest.java
  src/test/java/foodwhere/testutil/ReviewBuilder.java
  src/test/java/foodwhere/testutil/TypicalReviews.java
Labels: type.Task, priority.High

#134 Modify model data classes to include review related method
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/test/java/foodwhere/logic/commands/SAddCommandTest.java
Labels: type.Task, priority.High

#138 Modify user interface and add Review methods
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/resources/view/ReviewListCard.fxml
  src/test/java/foodwhere/logic/commands/SAddCommandTest.java
Labels: type.Task, priority.High

#136 Modify user guide with latest command formats
  docs/UserGuide.md
  docs/images/help.png
  docs/images/helpMessage.png
  docs/images/sadd.png
Labels: type.Task, priority.Medium

#140 Add review related test cases for StallTest
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/test/java/foodwhere/model/stall/StallTest.java
  src/test/java/foodwhere/testutil/StallBuilder.java
  src/test/java/foodwhere/testutil/TestUtil.java
Labels: type.Task, priority.Medium

#142 Modify sample data and JAR details
  build.gradle
  docs/UserGuide.md
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/commands/SAddCommand.java
  src/main/java/foodwhere/model/UserPrefs.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonSerializableAddressBook.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
Labels: type.Task, priority.High

#144 Modify user guide formatting and command details
  docs/UserGuide.md
Labels: type.Bug, priority.Medium, severity.VeryLow

#150 Modify Detail.java to Tag.java
  docs/UserGuide.md
  src/main/java/foodwhere/logic/commands/EditCommand.java
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/commands/SAddCommand.java
  src/main/java/foodwhere/logic/parser/CliSyntax.java
  src/main/java/foodwhere/logic/parser/EditCommandParser.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/logic/parser/RAddCommandParser.java
  src/main/java/foodwhere/logic/parser/SAddCommandParser.java
  src/main/java/foodwhere/model/commons/Detail.java
  src/main/java/foodwhere/model/commons/Tag.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedDetail.java
  src/main/java/foodwhere/storage/JsonAdaptedReview.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/main/java/foodwhere/storage/JsonAdaptedTag.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
  src/main/resources/view/ReviewListCard.fxml
  src/main/resources/view/StallListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStallAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStallsAddressBook.json
  src/test/java/foodwhere/logic/LogicManagerTest.java
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/EditCommandTest.java
  src/test/java/foodwhere/logic/commands/EditStallDescriptorTest.java
  src/test/java/foodwhere/logic/parser/ArgumentTokenizerTest.java
  src/test/java/foodwhere/logic/parser/EditCommandParserTest.java
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/logic/parser/SAddCommandParserTest.java
  src/test/java/foodwhere/model/AddressBookTest.java
  src/test/java/foodwhere/model/detail/DetailTest.java
  src/test/java/foodwhere/model/review/ReviewTest.java
  src/test/java/foodwhere/model/review/UniqueReviewListTest.java
  src/test/java/foodwhere/model/stall/StallTest.java
  src/test/java/foodwhere/model/stall/UniqueStallListTest.java
  src/test/java/foodwhere/model/tag/TagTest.java
  src/test/java/foodwhere/storage/JsonAdaptedReviewTest.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
  src/test/java/foodwhere/testutil/EditStallDescriptorBuilder.java
  src/test/java/foodwhere/testutil/ReviewBuilder.java
  src/test/java/foodwhere/testutil/StallBuilder.java
  src/test/java/foodwhere/testutil/StallUtil.java
  src/test/java/foodwhere/testutil/TypicalReviews.java
  src/test/java/foodwhere/testutil/TypicalStalls.java
Labels: type.Task, priority.High

#151 Add Rating class to Review
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/parser/CliSyntax.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/logic/parser/RAddCommandParser.java
  src/main/java/foodwhere/model/review/Rating.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedReview.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ReviewListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalStallsAddressBook.json
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/model/review/RatingTest.java
  src/test/java/foodwhere/storage/JsonAdaptedReviewTest.java
  src/test/java/foodwhere/testutil/ReviewBuilder.java
  src/test/java/foodwhere/testutil/TypicalReviews.java
Labels: type.Task, priority.High

#158 Add parser tests
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/parser/AddressBookParserTest.java
  src/test/java/foodwhere/logic/parser/RAddCommandParserTest.java
  src/test/java/foodwhere/testutil/StallUtil.java
Labels: type.Task, priority.High

#162 Modify user interface to show stars for Ratings
  copyright.txt
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
  src/main/resources/images/stars_0.png
  src/main/resources/images/stars_1.png
  src/main/resources/images/stars_2.png
  src/main/resources/images/stars_3.png
  src/main/resources/images/stars_4.png
  src/main/resources/images/stars_5.png
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/ReviewListCard.fxml
  src/main/resources/view/StallListCard.fxml
Labels: type.Task, priority.High

#167 Modify SampleDataUtil.java to change date format
  src/main/java/foodwhere/model/util/SampleDataUtil.java
Labels: type.Bug, priority.High, severity.High

#168 Add edit stall function
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/logic/parser/AddressBookParser.java
  src/main/java/foodwhere/logic/parser/SEditCommandParser.java
  src/test/java/foodwhere/logic/commands/CommandTestUtil.java
  src/test/java/foodwhere/logic/commands/EditStallDescriptorTest.java
  src/test/java/foodwhere/logic/commands/SEditCommandTest.java
  src/test/java/foodwhere/logic/parser/AddressBookParserTest.java
  src/test/java/foodwhere/logic/parser/SEditCommandParserTest.java
  src/test/java/foodwhere/testutil/EditStallDescriptorBuilder.java
  src/test/java/foodwhere/testutil/StallUtil.java
Labels: type.Task, priority.High

#171 Add sort by name function for stalls and reviews
  src/main/java/foodwhere/logic/commands/RSortCommand.java
  src/main/java/foodwhere/logic/commands/SSortCommand.java
  src/main/java/foodwhere/logic/parser/AddressBookParser.java
  src/main/java/foodwhere/model/AddressBook.java
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/model/review/UniqueReviewList.java
  src/main/java/foodwhere/model/stall/UniqueStallList.java
  src/test/java/foodwhere/logic/commands/SAddCommandTest.java
Labels: type.Task, priority.High

#172 Add Edit Review functionality
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/main/java/foodwhere/logic/parser/AddressBookParser.java
  src/main/java/foodwhere/logic/parser/REditCommandParser.java
Labels: type.Task, priority.High

#169 Add copying of stall and review details from user interface
  docs/images/Ui.png
  docs/images/sadd.png
  src/main/java/foodwhere/ui/CopyMenuItem.java
  src/main/java/foodwhere/ui/ReviewListPanel.java
  src/main/java/foodwhere/ui/StallListPanel.java
  src/main/resources/view/ReviewListPanel.fxml
  src/main/resources/view/StallListPanel.fxml
Labels: type.Task, priority.High

#184 Update build.gradle to enable assertions
  build.gradle
Labels: type.Task, priority.High

#180 Update Developer Guide on User Interface and Review
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/ModelReviewClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ModelReviewClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High

#186 Modify DG (Model and Implementation sections)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddReviewActivityDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddReview.png
  docs/images/AddReviewActivityDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation, type.Task, priority.High

#188 Fix incorrect date format in RAdd prompt
  src/main/java/foodwhere/logic/commands/RAddCommand.java
Labels: type.Bug, severity.Medium

#191 Update MainApp version number for trial release
  src/main/java/foodwhere/MainApp.java
Labels: type.Task, priority.High

#192 Update Developer Guide for Storage and set links correctly
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: documentation, type.Task

#194 Update developer guide for review
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: documentation, type.Task, priority.High

#196 Edit parser to parse correct review prefixes
  src/main/java/foodwhere/logic/parser/REditCommandParser.java
  src/test/java/foodwhere/logic/commands/RAddCommandTest.java
Labels: type.Bug, severity.High

#204 Add Review from Stall into JsonAdaptedStall
  src/main/java/foodwhere/storage/JsonAdaptedReview.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/test/java/foodwhere/storage/JsonAdaptedReviewTest.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
Labels: bug, priority.High

#198 Fix Panel throwing NullPointerException
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/ui/ReviewListPanel.java
  src/main/java/foodwhere/ui/StallListPanel.java
Labels: type.Bug, priority.High, severity.Medium

#209 Modify and add sort functions
  src/main/java/foodwhere/logic/commands/RSortCommand.java
  src/main/java/foodwhere/logic/commands/SSortCommand.java
  src/main/java/foodwhere/logic/parser/AddressBookParser.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/logic/parser/RSortCommandParser.java
  src/main/java/foodwhere/logic/parser/SSortCommandParser.java
  src/main/java/foodwhere/model/AddressBook.java
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/model/review/UniqueReviewList.java
  src/main/java/foodwhere/model/review/comparator/DateComparator.java
  src/main/java/foodwhere/model/review/comparator/NameComparator.java
  src/main/java/foodwhere/model/review/comparator/RatingComparator.java
  src/main/java/foodwhere/model/review/comparator/ReviewsComparatorList.java
  src/main/java/foodwhere/model/stall/UniqueStallList.java
  src/main/java/foodwhere/model/stall/comparator/NameComparator.java
  src/main/java/foodwhere/model/stall/comparator/StallsComparatorList.java
  src/test/java/foodwhere/logic/commands/SAddCommandTest.java
Labels: type.Task, priority.High

#211 Make Reviews follow new Stall name on rename
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/model/review/ReviewBuilder.java
  src/main/java/foodwhere/model/stall/StallBuilder.java
  src/test/java/foodwhere/logic/commands/RAddCommandTest.java
  src/test/java/foodwhere/logic/parser/AddressBookParserTest.java
  src/test/java/foodwhere/logic/parser/RAddCommandParserTest.java
  src/test/java/foodwhere/model/AddressBookTest.java
  src/test/java/foodwhere/model/review/ReviewTest.java
  src/test/java/foodwhere/model/review/UniqueReviewListTest.java
  src/test/java/foodwhere/model/stall/StallBuilderTest.java
  src/test/java/foodwhere/testutil/TypicalReviews.java
Labels: bug, priority.High

#174 Add functionality for find reviews
  docs/UserGuide.md
  src/main/java/foodwhere/commons/core/Messages.java
  src/main/java/foodwhere/logic/commands/RFindCommand.java
  src/main/java/foodwhere/logic/parser/AddressBookParser.java
  src/main/java/foodwhere/logic/parser/RFindCommandParser.java
  src/main/java/foodwhere/model/review/NameContainsStallPredicate.java
  src/main/java/foodwhere/model/stall/NameContainsKeywordsPredicate.java
  src/test/java/foodwhere/logic/commands/RFindCommandTest.java
  src/test/java/foodwhere/logic/parser/AddressBookParserTest.java
  src/test/java/foodwhere/logic/parser/RFindCommandParserTest.java
  src/test/java/foodwhere/model/review/NameContainsStallPredicateTest.java
  src/test/java/foodwhere/model/stall/NameContainsKeywordsPredicateTest.java
  src/test/java/foodwhere/testutil/TypicalReviews.java
Labels: type.Task, priority.High

#218 Add screenshot of Clipboard feature
  src/main/java/foodwhere/ui/HelpWindow.java
  src/main/resources/images/clipboard.png
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/test/java/foodwhere/model/review/NameContainsStallPredicateTest.java
Labels: type.Task, priority.Medium

#221 Relax Stall notion of equality to include Address
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/model/AddressBook.java
  src/main/java/foodwhere/model/Model.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/review/ReviewBuilder.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedReview.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStallAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStallsAddressBook.json
  src/test/java/foodwhere/logic/commands/RAddCommandTest.java
  src/test/java/foodwhere/logic/commands/SAddCommandTest.java
  src/test/java/foodwhere/model/AddressBookTest.java
  src/test/java/foodwhere/model/stall/StallTest.java
  src/test/java/foodwhere/model/stall/UniqueStallListTest.java
  src/test/java/foodwhere/storage/JsonAdaptedReviewTest.java
  src/test/java/foodwhere/testutil/TypicalReviews.java
Labels: type.Task, priority.High

#224 Modify Address class into model.common and ReviewListCard
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/sadd.png
  src/main/java/foodwhere/logic/commands/RAddCommand.java
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/logic/parser/SAddCommandParser.java
  src/main/java/foodwhere/model/commons/Address.java
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/review/ReviewBuilder.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/model/stall/StallBuilder.java
  src/main/java/foodwhere/model/util/SampleDataUtil.java
  src/main/java/foodwhere/storage/JsonAdaptedReview.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/resources/view/ReviewListCard.fxml
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/logic/parser/SAddCommandParserTest.java
  src/test/java/foodwhere/logic/parser/SEditCommandParserTest.java
  src/test/java/foodwhere/model/common/AddressTest.java
  src/test/java/foodwhere/model/common/TagTest.java
  src/test/java/foodwhere/storage/JsonAdaptedReviewTest.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
  src/test/java/foodwhere/testutil/EditStallDescriptorBuilder.java
Labels: type.Task, priority.High

#227 Modify help screenshot and update summary table
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Task, priority.High

#228 Fix bug in SFind and RFind commands
  src/main/java/foodwhere/logic/parser/ParserUtil.java
  src/main/java/foodwhere/logic/parser/RFindCommandParser.java
  src/main/java/foodwhere/logic/parser/SFindCommandParser.java
  src/test/java/foodwhere/logic/parser/ParserUtilTest.java
  src/test/java/foodwhere/logic/parser/RFindCommandParserTest.java
  src/test/java/foodwhere/logic/parser/SFindCommandParserTest.java
  src/test/java/foodwhere/model/stall/StallContainsKeywordsPredicateTest.java
Labels: type.Bug

#230 Update User Guide for SFind and RFind
  docs/UserGuide.md
Labels: documentation, priority.High

#233 Update UserGuide with sedit and redit details
  docs/UserGuide.md
Labels: documentation, type.Task, priority.Low

#235 Fix user guide for incorrect date format
  docs/UserGuide.md
Labels: documentation, type.Bug, severity.Low

#237 Add copying of Address for Review
  src/main/java/foodwhere/ui/CopyMenuItem.java
  src/main/java/foodwhere/ui/ReviewListPanel.java
Labels: type.Task, priority.High

#240 Update User Guide to include ssort and rsort commands
  docs/UserGuide.md
  src/main/java/foodwhere/model/review/comparator/NameComparator.java
  src/main/java/foodwhere/model/review/comparator/ReviewsComparatorList.java
  src/main/java/foodwhere/model/stall/comparator/NameComparator.java
  src/main/java/foodwhere/model/stall/comparator/StallsComparatorList.java
Labels: documentation, type.Task, priority.High

#242 Update README with latest features of FoodWhere
  README.md
Labels: documentation, type.Task, priority.High

#244 Update User Guide for 1.3
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: documentation, priority.High

#247 Fix rsort/ssort tables
  docs/UserGuide.md
  docs/images/sadd.png
Labels: bug, documentation, priority.High

#250 Update MainApp version number
  src/main/java/foodwhere/MainApp.java
Labels: type.Task, priority.High

#252 Modify tag string returned by Copy Tag in User Interface
  src/main/java/foodwhere/model/review/Review.java
  src/main/java/foodwhere/model/stall/Stall.java
  src/main/java/foodwhere/ui/CopyMenuItem.java
  src/main/java/foodwhere/ui/ReviewCard.java
  src/main/java/foodwhere/ui/StallCard.java
Labels: type.Task, priority.Medium

#253 Update MainApp with version number 1.3.1
  src/main/java/foodwhere/MainApp.java
Labels: type.Task, priority.High

#255 Modify MainApp for AddressBook to FoodWhere
  src/main/java/foodwhere/MainApp.java
  src/main/java/foodwhere/logic/Logic.java
  src/main/java/foodwhere/logic/commands/ClearCommand.java
  src/main/java/foodwhere/logic/commands/ExitCommand.java
  src/main/java/foodwhere/logic/commands/REditCommand.java
  src/main/java/foodwhere/logic/commands/RFindCommand.java
  src/main/java/foodwhere/logic/commands/RSortCommand.java
  src/main/java/foodwhere/logic/commands/SEditCommand.java
  src/main/java/foodwhere/logic/commands/SFindCommand.java
  src/main/java/foodwhere/logic/commands/SSortCommand.java
  src/main/java/foodwhere/model/ModelManager.java
  src/main/java/foodwhere/model/commons/Address.java
  src/main/java/foodwhere/model/commons/Name.java
  src/main/java/foodwhere/model/commons/Tag.java
  src/main/java/foodwhere/model/review/Content.java
  src/main/java/foodwhere/model/review/Rating.java
  src/main/java/foodwhere/storage/AddressBookStorage.java
  src/main/java/foodwhere/storage/JsonAddressBookStorage.java
  src/main/java/foodwhere/storage/JsonSerializableAddressBook.java
  src/main/java/foodwhere/storage/StorageManager.java
Labels: type.Bug, priority.High, severity.VeryLow

#258 Improve test coverage in commons and storage
  src/main/java/foodwhere/commons/core/GuiSettings.java
  src/main/java/foodwhere/commons/core/Version.java
  src/main/java/foodwhere/storage/JsonAdaptedStall.java
  src/test/java/foodwhere/commons/core/ConfigTest.java
  src/test/java/foodwhere/commons/core/GuiSettingsTest.java
  src/test/java/foodwhere/commons/core/VersionTest.java
  src/test/java/foodwhere/storage/JsonAdaptedStallTest.java
  src/test/java/foodwhere/storage/JsonUserPrefsStorageTest.java
  src/test/java/foodwhere/storage/StorageManagerTest.java
Labels: type.Task, priority.Medium

#259 Add use case for clear command in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation, type.Task, priority.High

#321 Add implementation details of rlist in DG
  docs/DeveloperGuide.md
  docs/diagrams/ListReviewActivityDiagram.puml
  docs/images/ListReview.png
  docs/images/ListReviewActivityDiagram.png
Labels: documentation, type.Task, priority.High

#319 Add implementation details of rdel in UG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteReviewActivityDiagram.puml
  docs/images/DeleteReview.png
  docs/images/DeleteReviewActivityDiagram.png
Labels: documentation, type.Task, priority.High

#324 Fix User Guide documentation bugs
  docs/UserGuide.md
Labels: documentation, type.Task, priority.High, severity.Medium

#270 Update use cases for edit food stalls and review
  docs/DeveloperGuide.md
Labels: documentation, type.Task, priority.High

#317 Add REdit implementation details in DG
  docs/DeveloperGuide.md
  docs/diagrams/EditReviewActivityDiagram.puml
  docs/diagrams/REditSequenceDiagram.puml
  docs/images/EditReview.png
  docs/images/EditReviewActivityDiagram.png
  docs/images/REditSequenceDiagram.png
Labels: documentation, type.Task, priority.High
